Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
  - src/cliq.cr
  Enabled: true
  Severity: Convention

Lint/NotNil:
  Enabled: false
